version: "3.9"
# version of docker compose syntax to be used

services:
  app:
  build:
    context: .
    # . is current directory 
  ports:
    - "8000:8000"
  # maps port local machine: port in docker container
  volumes:
    - ./app:/app
  # maps directory from system into docker container to automatically sync code 
  command: >
    sh -c "python manage.py runserver 0.0.0.0:8000"
  # command used to run the service, can be overriden using RUN command in docker file 
